### ISSUE TITLE
Mod Roller rolling same mods

### ISSUE THREAD

**Issue by Maplernothaxor** [NickRyder/PoECraft#1]
Hey, I tried running the dense fossil example script and the mod roller seems to roll the exact same 4 mods every time and occasionally rolls a different 5th/6th. Is this an issue with the new patch?

Also, special items (like the convoking wand) which add mods to the mod pool aren't supported right now. Are there future plans to support them?

Love this work and look forward to testing new crafting combinations in the future!

**Comment by Maplernothaxor** [comment]
Hey, just checking if I am doing something wrong or if there is an issue with the mod roller? I'm just using the example scripts and the roller just rolls the same thing every time.

Keen to use this library so would love a response.

**Comment by NickRyder** [comment]
@Maplernothaxor The prng generator has a fixed seed, so the first item will be the same. The number of mods uses the python library which doesn't use a fixed seed. 

I should probably reseed the prng generator for each new pass - but it's low on my priority list since I don't think it affects the conclusions.
